project_id = "lqcxabgbknmitgdyimeb"

[functions.enhance-with-gemini]
verify_jwt = false

[functions.fetch-team-roster]
verify_jwt = false

[functions.get-transcript]
verify_jwt = false

[functions.transcribe-commentary]
verify_jwt = false

[functions.transcribe-huggingface]
verify_jwt = false